### ISSUE TITLE
HARNESS-058: the mandated verification gate is unrunnable where the work happens — four agents bypassed it in one day

### ISSUE THREAD

**Issue by woojubb** [woojubb/robota#1571]
# HARNESS-058 — the mandated gate is unrunnable where the work happens

Existing backlog item (`.agents/backlog/HARNESS-058-verify-like-ci-cannot-go-green-in-a-worktree.md`,
status `todo`, created 2026-07-28). Filed as an issue now because it has just been measured again, at
much larger scale, and the cost it predicted has arrived exactly as written.

## What the item predicted

> A gate that cannot go green on a correct branch is a standing incentive to skip it.

> Three separate agents hit the same wall this session and each resolved it differently — one ran
> `pnpm install && pnpm build` first, one reported the failures as environment artefacts, one nearly
> recorded them as real. **The verification story for a fresh worktree is undefined, so every agent
> invents one.**

## What happened on 2026-08-01

Four subagents ran in parallel worktrees, each on a separate item, none aware of the others.
**All four hit it. All four pushed with `--no-verify`.** Each independently diagnosed it, each
correctly, each spending real effort proving the reds were not its own:

| agent | what it reported |
| --- | --- |
| HARNESS-062 | 3 failed; `git diff origin/develop` on those files empty; pushed `--no-verify` |
| INFRA-077 | 4 failed; proven identical on unmodified develop by `git checkout origin/develop -- .claude/hooks`; pushed `--no-verify` |
| INFRA-075 | 3 failed; proven by stashing the diff; pushed `--no-verify` |
| INFRA-074 | 3 failed; baseline 1812/3 same 3; pushed `--no-verify`; named this item by number |

The husky pre-push gate runs the full harness suite. In a worktree the suite cannot go green, so the
gate refuses every push, so every agent bypasses it. **The gate is now training the agents that use
it to route around it** — which is worse than the failures it started as, because the next bypass
will be over a real finding and no one will look twice.

## The faces measured today

| face | cause |
| --- | --- |
| 3 × `worktree-cwd-guard` FAIL-SAFE cases | the hook reads its OWN directory to decide the session's identity, so a worktree-resident copy self-reports a worktree session — **fixed in #1567** |
| `listNodeModulesOwners` | wants per-package `node_modules`, absent in a fresh worktree |
| `dist` scan | nothing built in this checkout |
| `doc-examples` scan | `tsc` not installed in this checkout |
| `typecheck` before `build` | the item's original finding: stage order in `ci-mirror-map.mjs` |

A sibling worktree is worse than a nested one, not better: without any install, `vitest` cannot start
at all (`Could not resolve 'vitest/config'`). Nested worktrees only run because module resolution
walks up into the parent clone's `node_modules` — which is also why the hook path differs and the
three guard tests fail. **The two configurations fail in opposite directions, and neither is
documented.**

## Direction, unchanged from the item

- Order stages so a prerequisite runs before what needs it, or make the dependent stage state its
  prerequisite and fail with that reason rather than a type error.
- Decide what a fresh worktree owes before verification and put it in **one place agents follow**.
  Today the answer lives in whoever last worked it out — measured four times over, four times
  differently, in a single day.
- The distinction that must appear in the output: **failed because the code is wrong** vs **failed
  because this tree was never built**. The second is not a verdict on the change, and today it is
  reported as if it were.

## Done when

- `verify-like-ci` passes on a docs-only branch in a freshly-created worktree, proven by running it
  there.
- A genuine failure still fails, proven RED, so the fix is not "stop checking".
- An unbuilt tree produces a message naming the missing prerequisite, not a downstream type error.
- **Added:** a parallel subagent completes an item without `--no-verify`, proven by the push
  succeeding through the gate.

**Comment by woojubb** [comment]
## One face closed, measured; a second face found by the same measurement

### The worktree-cwd-guard face — closed by #1567, verified rather than assumed

Both blocked agents were told to rebase onto the merged #1567, run the gate, and **report instead of
bypassing if anything stayed red**. Both did, and both reported the same before/after from inside a
worktree:

| | before #1567 | after |
| --- | --- | --- |
| INFRA-077 agent — `scripts/harness/__tests__/` | 1878 passed, **3 failed** | **1881 / 1881** |
| INFRA-075 agent — same suite | 3 failed | **2032 / 2032** |
| `pnpm harness:pre-push` | red for both | **green (rc=0)** for both |

**Both then pushed with the gate passing on its own — no `--no-verify`.** That is this issue's added
"done when" criterion met for this face: a parallel subagent completed an item and the push went
through the gate.

Worth stating because it is the part that generalises: the instruction that produced this was *"do
not bypass — if it is still red, stop and tell me what"*. Four agents bypassed when the gate was
broken and no one had said that; two stopped and reported once it was said and the gate was fixed.
The rule was never the missing piece on its own — a gate that cannot go green plus an instruction not
to bypass just stops all work. Both had to change.

### The face the same run exposed

With the three tests fixed, the gate got **further** and then died somewhere new — in a fresh
worktree that has never been built:

```
▶ CLI smoke check (cli:dev --version)
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
  '…/packages/agent-command-workflows/node_modules/@robota-sdk/dag-core/dist/node/index.js'
```

Reported independently by both agents. `pnpm build` clears it and the gate then goes green
(`robota 3.0.0-beta.79`), and `pnpm harness:scan` goes from 83/84 to 84/84 with the same build.

This is precisely the direction already written into this item:

> The distinction that matters in the output: **failed because the code is wrong** vs **failed
> because this tree was never built**. The second is not a verdict on the change, and today it is
> reported as if it were.

A missing module path is not a message that names its prerequisite. It reads like a broken import in
the change under test, which is the same misreading the three guard tests produced, one stage later.

### Still open

- The CLI smoke check, and every stage after it, must say *"this tree has never been built — run
  `pnpm build`"* rather than surfacing the downstream error.
- `typecheck` (stage 5) still runs before `build` (stage 6) in `ci-mirror-map.mjs` — the original
  finding, unchanged.
- A **sibling** worktree (outside the repo) is worse than a nested one and neither is documented:
  measured today, `vitest` cannot start there at all (`Could not resolve 'vitest/config'`) because a
  fresh worktree has no `node_modules` and pnpm workspaces do not share one. Nested worktrees only
  run because module resolution walks up into the parent clone — which is also why the hook's own
  path differed and the three guard tests failed. **The two configurations fail in opposite
  directions.**

**Comment by woojubb** [comment]
Resolved by #1577, merged. Verified on `origin/develop`: `scripts/harness/tree-prerequisites.mjs` exists, and the stage table now reads `build` at 5 and `typecheck` at 6, with all six build-output consumers declaring `needsBuildOutput` — the original 2026-07-28 finding, closed.

## Before, in a real fresh nested worktree at develop with zero changes

`pnpm harness:verify-like-ci` failed **7 of 11 stages**: `vitest: not found`, `ERR_MODULE_NOT_FOUND: @typescript/native-preview`, `tsgo: not found`, `tsdown: not found`, `6 of 82 scans failed`. **Not one names a prerequisite.**

A finding this issue did not have: in a NEVER-INSTALLED worktree `pnpm build` fails too. The primary missing prerequisite is the **install**; the missing-`dist` message quoted here comes from worktrees that were installed but not built. Both are covered.

## After

It refuses to run and names what is missing — `verify-like-ci did NOT run: this tree is missing a verification prerequisite. This is NOT a verdict on your change`, the tree path, whether it is nested inside its parent clone, why the install cannot be borrowed, and the exact command. Then, after doing only what it says: **`PASS — all 11 stage(s) passed`, EXIT=0**, on a docs-only branch in a freshly-created worktree — `pnpm build` never run by hand, because the reordered `build` stage does it.

## A genuine failure still fails, proven

A real type error in `packages/dag-core/src/` → `error TS2322` / `✗ typecheck`, exit 1, no prerequisite message. Unbuilt-tree paths are **failures, not skips**. The stage-order rule was red-proved before the fix (`expected [ 'typecheck' ] to deeply equal []`), and each stage's `needsBuildOutput` declaration is enforced by a test that forbids any such stage from preceding `build` **and** fails a stage that declares nothing — so it cannot decay back into a one-off swap.

## The two review rounds are the part worth keeping

**Reviewer disagreement, settled by measurement.** Two reviewers read the same `willBuild` line and reached opposite conclusions — one called it non-actionable, one a MUST. Rather than argue it, a real build regression was introduced in a fresh worktree and the output read: `examples-typecheck` printed twenty lines of type errors plus an actively wrong instruction to `npm i --save-dev @types/node`, and `binary-e2e` spent 20s driving a binary nobody built. Not a restatement of the build failure — **a different and wrong diagnosis**. Neither review predicted the blast radius: `typecheck` reported the real defect, and `scan-suite` was clean because it re-checks dist itself.

**And the gate refused work that needed none.** A delete-only push and a no-delta re-push skip verification entirely, yet the new prerequisite check ran BEFORE that decision — so in a fresh worktree, deleting a remote branch demanded a full install and build for a push with nothing to verify. Precisely the parallel-subagent scenario this item is about. Fixed, with the ORDERING pinned as an invariant rather than a fixed index, red-proved by restoring the old order inside the new structure (6 of 9 fail, and the three that keep passing are the ones proving the gate did not simply stop firing).

## A measurement pitfall recorded

The first red attempt ran the delete-only case in a worktree checked out at `origin/develop` — which **predates the gate** — and printed `skipped: delete-only push`, making the finding look wrong. **Measuring a gate's behaviour on a tree that does not contain the gate produces a confident false negative.**

## Still open, tracked separately

The stash/reflog sharing this issue's comments surfaced is **#1584**, and the `branch-guard` override reflex during a wave is noted there.
